# Generated by Django 4.2 on 2024-02-09 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_pet_age_pet_interests_pet_precautions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='age',
            new_name='birth_year',
        ),
    ]
