# Generated by Django 4.2 on 2024-02-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_rename_age_pet_birth_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='category',
            field=models.CharField(default='cat', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='PetBreed',
        ),
        migrations.DeleteModel(
            name='PetCategory',
        ),
    ]
