# Generated by Django 4.2 on 2024-02-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_pet_category_alter_pet_breed_delete_petbreed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='open_to_adopt',
            field=models.BooleanField(default=False),
        ),
    ]
